config/routes.rb
PerformanceTest::Application.routes.draw do
  root :to => "accounts#index"
  resources :accounts
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :sub_accounts, :class_name => "Account", :foreign_key => "parent_account_id"
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    
  end
  def show
    @account = Account.find(params[:id].to_i)
    #@accounts = Account.first.sub_accounts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.haml
%h1 Index page

= link_to "Click here to load resources", account_path(1)

app/views/accounts/show.html.haml
%h1 Direct Customers for #{@account.company_name}
%table.light
  %tr
    %th Company Name
    %th Prim H_S Name
    %th Prim H_S Email
  - @account.sub_accounts.each do |account|
    %tr
      %td= account.company_name
      %td= account.name
      %td= account.email      

-# @accounts.each do |account|
  = @account.company_name
  %br/

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "Eebos Performance Tests"
    = csrf_meta_tag
    = stylesheet_link_tag :all


  %body
    #outer_container
      #inner-container
        #header          
          #logo= image_tag "master.png"
          .clear

        .clear
        = yield